#line 1 "D:\\FreeCAD-0.19.1-build\\src\\Mod\\kawasaki\\kawasaki\\\\kawasaki\\grammar\\lexer.cpp"

#line 3 "D:\\FreeCAD-0.19.1-build\\src\\Mod\\kawasaki\\kawasaki\\\\kawasaki\\grammar\\lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::streambuf* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int Lexer::yylex()

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 111
#define YY_END_OF_BUFFER 112
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[441] =
    {   0,
        0,    0,    2,    2,    0,    0,  112,  111,   49,    4,
      111,  101,  108,   99,  100,  104,  102,   98,  103,  111,
      111,    7,  105,    1,  106,   91,  107,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,   96,
       97,  110,  110,  110,  110,    7,    2,    3,  111,    0,
        0,    0,    0,    0,   49,    0,    6,    0,    0,    0,
        0,    0,    0,  110,  110,  110,  110,  110,  110,  109,
      110,    0,    7,    7,  110,    5,   95,   94,   92,   93,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,

      110,  110,   14,  110,  110,  110,  110,   57,  110,  110,
      110,  110,  110,  110,  110,  110,  110,   16,  110,  110,
      110,  110,  110,  110,  110,  110,   48,   42,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,   87,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,    8,    0,
        2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    6,    0,  110,  110,  110,  110,  110,  110,
        0,  110,    5,  110,  110,  110,   41,   46,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,   39,

      110,  110,   85,  110,  110,  110,  110,  110,  110,  110,
      110,    0,   12,  110,  110,  110,  110,  110,  110,  110,
       36,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,   30,  110,  110,  110,  110,  110,
       40,    0,    0,    0,    0,   40,    0,    0,    0,    0,
       40,  110,  110,  110,  110,  110,    0,    7,  110,  110,
      110,  110,   27,   25,  110,  110,   44,   43,  110,  110,
       69,  110,   17,  110,   88,   34,   61,   26,  110,  110,
      110,  110,  110,    0,   82,   47,  110,  110,  110,  110,
      110,  110,  110,  110,   90,   24,  110,  110,  110,   18,

       28,  110,   54,  110,   29,  110,  110,  110,  110,  110,
       10,   11,    0,    0,    0,    0,    0,    0,    0,    0,
      110,  110,  110,  110,  110,  110,  110,   59,  110,   60,
      110,  110,  110,   68,   55,  110,   37,  110,  110,   56,
        0,   86,   70,   20,   31,  110,   15,  110,   63,   38,
      110,  110,  110,   76,   23,   32,   58,   45,  110,   19,
      110,    0,    0,   50,    0,    0,    0,   50,    0,  110,
      110,   50,  110,  110,   53,  110,   84,   65,  110,  110,
       64,   66,  110,   83,    0,   21,   33,  110,  110,  110,
      110,  110,   71,    9,   52,    0,    0,   52,    0,    0,

       52,  110,  110,   13,  110,  110,  110,   72,    0,   73,
       74,  110,  110,  110,  110,  110,   35,   51,   35,   51,
       35,   51,   67,  110,   22,    0,  110,  110,   79,   77,
      110,   62,   75,   78,  110,  110,  110,   80,   81,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,    1,   52,    1,   39,   53,   39,   54,

       55,   39,   39,   39,   56,   39,   39,   39,   57,   58,
       59,   39,   39,   60,   39,   61,   62,   63,   39,   64,
       39,   39,    1,   65,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    3,    3,    3,    1,    1,    1,
        1,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    5,    1,
        1,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[450] =
    {   0,
        0,   50,  810,  809,    0,    0,  811,   41,   67,   69,
       71,   51,   87,   91,  103,  107,  119,  123,  152,  179,
      148,  186,  198,  202,  223,  227,  239,  249,  261,  280,
      273,  290,  302,  309,  321,  328,  340,  344,  360,  367,
      379,  386,  398,  402,  417,  438,  140,  451,  457,  465,
      477,  481,  167,  483,  531,  581,    0,  814,  814,  774,
      772,  768,  780,  764,   74,   70,  814,  102,  150,   76,
       83,  173,   92,    0,  769,  767,  763,  775,  759,  814,
      773,   69,  236,  518,  759,    0,  814,  814,  814,  814,
        0,  773,  761,  759,   57,   75,  755,  767,  751,  751,

      749,  763,    0,  754,   56,   68,  747,    0,  210,  746,
      760,  751,  748,  743,  740,  113,  746,    0,  742,  742,
      740,  750,  739,  761,  748,  739,    0,  745,  728,  739,
      177,  735,  130,  737,  738,   97,  146,  743,  727,  724,
      736,  725,  235,  738,  722,  717,  724,  239,  726,  699,
      691,  698,    0,  717,  715,  711,  723,  707,  814,  137,
        0,  722,  716,  709,  722,  704,  206,  323,  269,  341,
      353,  265,  282,  294,  717,  711,  704,  717,  699,  713,
      455,  714,    0,  693,  706,  711,    0,    0,  706,  691,
      708,  693,  695,  701,  690,  684,  680,  680,  696,    0,

      681,  694,    0,  683,  692,  691,  679,  672,  677,  676,
      669,  355,    0,  678,  670,  674,  673,  667,  664,  678,
      669,  677,  665,  664,  670,  648,  676,  662,  663,  660,
      668,  663,  666,  661,  648,  661,  655,  635,  626,  632,
      814,  649,  655,  649,  651,  287,  373,  427,  411,  366,
        0,  645,  651,  645,  647,  640,  435,  514,  640,  635,
      638,  626,    0,    0,  213,  628,    0,    0,  633,  635,
        0,  607,    0,  606,    0,    0,    0,    0,  592,  604,
      590,  606,  601,  596,  814,    0,  599,  583,  582,  596,
      580,  576,  594,  590,    0,    0,  573,  497,  569,    0,

        0,  571,    0,  568,    0,  575,  580,  574,  576,  546,
        0,    0,  558,  559,  552,  556,  482,  450,  512,  504,
      549,  550,  548,  552,  561,  545,  558,    0,  538,    0,
      551,  539,  540,    0,    0,  538,    0,  537,  530,    0,
      532,    0,  553,    0,    0,  525,    0,  517,    0,    0,
      301,  500,  189,    0,    0,    0,    0,    0,  465,    0,
      441,  457,  471,  814,  462,  516,  532,  429,  535,  432,
      443,    0,  431,  426,    0,  421,    0,    0,  400,  407,
        0,    0,  386,  814,  504,    0,    0,  375,  374,  364,
      352,  356,    0,    0,  814,  339,  324,  506,  545,  561,

        0,  317,  310,    0,  276,  275,  282,    0,  272,  814,
      814,  253,  246,  228,  231,  193,  814,  814,  555,  556,
        0,    0,    0,  187,    0,  165,  154,  147,    0,    0,
      115,    0,  814,    0,  131,   76,   73,    0,    0,  814,
      635,  640,  645,  647,  650,  652,  656,  661,  666
    } ;

static const flex_int16_t yy_def[450] =
    {   0,
      440,    1,  441,  441,  442,  442,  440,  440,  440,  440,
      443,  444,  444,  440,  440,  440,  440,  440,  440,  444,
      440,  440,  440,  440,  440,  440,  440,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,   45,   45,   45,   45,  440,
      440,   45,   45,   45,  446,  440,  447,  440,  440,  440,
      440,  440,  440,  440,  440,  443,  440,  443,  443,  443,
      443,  443,  448,  445,  445,  445,  445,  445,  445,  440,
      445,  440,  440,  440,  445,  449,  440,  440,  440,  440,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  440,  440,
      447,  440,  440,  440,  440,  440,  443,  443,  443,  443,
      443,  443,  443,  448,  445,  445,  445,  445,  445,  445,
      440,  445,  449,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  440,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      440,  440,  440,  440,  440,  443,  443,  443,  443,  443,
      445,  445,  445,  445,  445,  445,  440,  440,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  440,  440,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  440,  440,  440,  440,  443,  443,  443,  443,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      440,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  440,  440,  440,  440,  443,  443,  443,  443,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  440,  440,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  440,  440,  440,  443,  443,  443,

      445,  445,  445,  445,  445,  445,  445,  445,  440,  440,
      440,  445,  445,  445,  445,  445,  440,  440,  443,  443,
      445,  445,  445,  445,  445,  440,  445,  445,  445,  445,
      445,  445,  440,  445,  445,  445,  445,  445,  445,    0,
      440,  440,  440,  440,  440,  440,  440,  440,  440
    } ;

static const flex_int16_t yy_nxt[880] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   38,   44,
       45,   46,   47,   48,   49,   38,   38,   38,   50,    8,
       51,    8,   38,   38,   38,   38,   38,   52,   38,   38,
       53,   38,   54,   38,   55,   56,   56,   60,   65,   65,
       65,   65,   61,   67,   67,   65,   65,   75,   62,   67,
       63,   64,   76,   84,   84,   84,   67,  185,   77,  193,
       78,   79,  195,   60,   66,  173,  194,   68,   61,   80,

      187,  186,   69,  175,   62,   67,   63,   64,   70,  170,
       71,   72,   81,   75,  439,  169,  438,   60,   76,   73,
       73,  188,   61,  222,   77,   73,   78,   79,   62,   60,
       63,   64,   73,   60,   61,  440,  177,  167,   61,  159,
       62,  174,   63,   64,   62,   60,   63,   64,  175,   60,
       61,   73,  205,   67,   61,  437,   62,  436,   63,   64,
       62,   86,   63,   64,   82,  175,   83,   83,   83,   91,
       91,  219,  223,  435,   60,  146,   67,   97,   60,   61,
      434,   91,  224,   61,   91,   62,  168,   63,   64,   62,
      160,   63,   64,   84,   84,   84,   91,   91,   82,   73,

       83,   83,   83,  178,   97,   75,  433,  217,   91,   67,
       76,   91,   60,  432,  171,  391,   77,   61,   78,   79,
       85,  151,   73,   62,   60,   63,   64,  440,   60,   61,
      392,  246,  197,   61,  431,   62,  178,   63,   64,   62,
      198,   63,   64,   87,   88,  330,  323,   89,   82,   60,
       83,   83,   83,   60,   61,   73,  430,  230,   61,   90,
       62,  178,   63,   64,   62,   60,   63,   64,   67,  236,
       61,  429,   67,   92,  175,   93,   62,  231,   63,   64,
       94,  428,   95,  100,   96,   67,   97,   93,   98,   99,
       67,  101,   94,  427,  426,  104,   66,  173,   97,  106,

      102,   99,  105,  107,   94,  248,   93,  103,  425,  108,
       97,   94,  109,   99,   73,  424,   93,   97,   73,   98,
       99,   94,  423,  110,  112,  111,   67,   97,   93,   98,
       99,   73,  113,   94,  388,   93,   73,  389,  114,   97,
       94,   98,   99,  174,   67,  115,   97,  116,   98,   99,
      422,  421,   94,  247,   93,  118,   67,  117,   97,   94,
       98,   99,  119,  249,  418,   97,   93,   98,   99,   67,
       93,   94,   73,  417,  120,   94,   67,   97,  416,   98,
       99,   97,  121,   98,   99,  122,   93,  415,  414,  284,
       73,   94,  250,   93,  123,  285,  320,   97,   94,   98,

       99,  124,   73,  125,   97,   93,   98,   99,  317,  413,
       94,  412,   93,  127,   67,   73,   97,   94,   98,   99,
      129,  126,   73,   97,   93,  128,   99,  408,  133,   94,
       67,  407,   67,   94,  130,   97,  406,  131,   99,   97,
      132,   98,   99,   93,  319,  405,  134,  135,   94,  258,
      258,  258,  404,   67,  136,  318,   98,   99,  137,  403,
       73,  138,  139,  140,  257,  402,  257,  141,   91,  258,
      258,  258,  401,  147,  142,   97,   73,  143,   73,   91,
       91,   91,  144,  148,  145,   67,  149,   91,   97,  367,
      397,   60,   91,  396,   97,   91,   61,  395,   91,   73,

      394,   91,   62,   60,   63,   64,  393,   67,   61,   67,
       91,   91,   91,   91,   62,   67,   63,   64,   97,   67,
       97,  351,   91,  366,   91,   91,  390,   91,  258,  258,
      258,   73,   84,   84,   84,   67,  352,  353,   67,  369,
      409,  152,  150,   91,  181,   91,   91,   91,   67,  410,
      387,  411,  368,   73,  399,   73,  398,  154,   67,   67,
      386,   73,  155,  400,   67,   73,  385,  384,  156,  383,
      157,  158,  181,  382,  381,  380,  379,  378,  377,  419,
      376,   73,   91,  159,   73,  375,  374,  373,  372,  371,
      370,  365,  364,   82,   73,   83,   83,   83,  363,  362,

      361,  420,  360,  359,   73,   73,  358,   60,  357,  356,
       73,  355,   61,  354,  350,  349,  348,  347,   62,  346,
       63,   64,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  160,   57,   57,   57,   57,   57,
       59,   59,   59,   59,   59,   66,   66,   66,   66,   66,
       74,   74,   91,   91,  153,  153,  161,  333,  161,  161,
      161,  172,  172,  172,  172,  172,  183,  332,  183,  183,
      183,  331,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,

      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  256,  255,  254,
      253,  252,  251,  245,  244,  243,  242,  241,  179,  178,
      177,  176,  175,  240,  239,  238,  237,  235,  234,  233,
      232,  229,  228,  227,  226,  225,  221,  220,  218,  216,
      215,  178,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  204,  203,  202,  201,  200,  199,  196,  192,  191,
      190,  189,  179,  178,  177,  176,  175,  184,  182,  180,

      179,  178,  177,  176,  175,  166,  165,  164,  163,  162,
      440,   58,   58,    7,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440
    } ;

static const flex_int16_t yy_chk[880] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    8,    9,    9,
       10,   10,    8,   66,   11,   65,   65,   12,    8,   70,
        8,    8,   12,   82,   82,   82,   71,   95,   12,  105,
       12,   12,  106,    9,   73,   73,  105,   11,    9,   12,

       96,   95,   11,  106,    9,   68,    9,    9,   11,   71,
       11,   11,   13,   13,  437,   70,  436,   14,   13,   66,
       11,   96,   14,  136,   13,   70,   13,   13,   14,   15,
       14,   14,   71,   16,   15,   13,  136,   68,   16,  160,
       15,   73,   15,   15,   16,   17,   16,   16,  116,   18,
       17,   68,  116,   69,   18,  435,   17,  431,   17,   17,
       18,   21,   18,   18,   19,  133,   19,   19,   19,   47,
       47,  133,  137,  428,   21,   47,   72,   47,   19,   21,
      427,   47,  137,   19,   47,   21,   69,   21,   21,   19,
      160,   19,   19,   20,   20,   20,   53,   53,   22,   69,

       22,   22,   22,  131,   53,   20,  426,  131,   53,  167,
       20,   53,   22,  424,   72,  353,   20,   22,   20,   20,
       20,   53,   72,   22,   23,   22,   22,   20,   24,   23,
      353,  167,  109,   24,  416,   23,  109,   23,   23,   24,
      109,   24,   24,   25,   25,  265,  265,   26,   83,   25,
       83,   83,   83,   26,   25,  167,  415,  143,   26,   27,
       25,  143,   25,   25,   26,   27,   26,   26,  172,  148,
       27,  414,  169,   28,  148,   28,   27,  143,   27,   27,
       28,  413,   28,   29,   28,  173,   28,   29,   28,   28,
      246,   29,   29,  412,  409,   30,  174,  174,   29,   31,

       29,   29,   30,   31,   31,  169,   30,   29,  407,   31,
       31,   30,   31,   31,  172,  406,   32,   30,  169,   30,
       30,   32,  405,   32,   33,   32,  168,   32,   33,   32,
       32,  173,   33,   33,  351,   34,  246,  351,   33,   33,
       34,   33,   33,  174,  170,   34,   34,   35,   34,   34,
      403,  402,   35,  168,   36,   36,  171,   35,   35,   36,
       35,   35,   37,  170,  397,   36,   37,   36,   36,  250,
       38,   37,  168,  396,   37,   38,  247,   37,  392,   37,
       37,   38,   39,   38,   38,   39,   39,  391,  390,  212,
      170,   39,  171,   40,   39,  212,  250,   39,   40,   39,

       39,   40,  171,   40,   40,   41,   40,   40,  247,  389,
       41,  388,   42,   42,  249,  250,   41,   42,   41,   41,
       43,   41,  247,   42,   43,   42,   42,  383,   44,   43,
      248,  380,  368,   44,   43,   43,  379,   43,   43,   44,
       43,   44,   44,   45,  249,  376,   45,   45,   45,  257,
      257,  257,  374,  318,   45,  248,   45,   45,   45,  373,
      249,   45,   46,   46,  181,  371,  181,   46,   46,  181,
      181,  181,  370,   48,   46,   46,  248,   46,  368,   46,
       48,   48,   46,   49,   46,  317,   49,   49,   48,  318,
      365,   50,   48,  363,   49,   48,   50,  362,   49,  318,

      361,   49,   50,   51,   50,   50,  359,  320,   51,  398,
       52,   52,   54,   54,   51,  319,   51,   51,   52,  366,
       54,  298,   52,  317,   54,   52,  352,   54,  258,  258,
      258,  317,   84,   84,   84,  367,  298,  298,  369,  320,
      385,   54,   52,   55,   84,   55,   55,   55,  399,  385,
      348,  385,  319,  320,  367,  398,  366,   55,  419,  420,
      346,  319,   55,  369,  400,  366,  343,  341,   55,  339,
       55,   55,   84,  338,  336,  333,  332,  331,  329,  399,
      327,  367,   55,   56,  369,  326,  325,  324,  323,  322,
      321,  316,  315,   56,  399,   56,   56,   56,  314,  313,

      310,  400,  309,  308,  419,  420,  307,   56,  306,  304,
      400,  302,   56,  299,  297,  294,  293,  292,   56,  291,
       56,   56,  290,  289,  288,  287,  284,  283,  282,  281,
      280,  279,  274,  272,   56,  441,  441,  441,  441,  441,
      442,  442,  442,  442,  442,  443,  443,  443,  443,  443,
      444,  444,  445,  445,  446,  446,  447,  270,  447,  447,
      447,  448,  448,  448,  448,  448,  449,  269,  449,  449,
      449,  266,  262,  261,  260,  259,  256,  255,  254,  253,
      252,  245,  244,  243,  242,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,

      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  211,  210,  209,  208,  207,  206,  205,  204,
      202,  201,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  186,  185,  184,  182,  180,  179,  178,
      177,  176,  175,  166,  165,  164,  163,  162,  158,  157,
      156,  155,  154,  152,  151,  150,  149,  147,  146,  145,
      144,  142,  141,  140,  139,  138,  135,  134,  132,  130,
      129,  128,  126,  125,  124,  123,  122,  121,  120,  119,
      117,  115,  114,  113,  112,  111,  110,  107,  104,  102,
      101,  100,   99,   98,   97,   94,   93,   92,   85,   81,

       79,   78,   77,   76,   75,   64,   63,   62,   61,   60,
        7,    4,    3,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440
    } ;

static const flex_int16_t yy_rule_linenum[111] =
    {   0,
      102,  104,  105,  115,  117,  118,  125,  130,  136,  137,
      138,  139,  140,  141,  142,  143,  144,  145,  146,  147,
      148,  149,  150,  151,  152,  153,  154,  155,  156,  157,
      158,  159,  160,  161,  162,  163,  164,  165,  166,  167,
      168,  169,  170,  171,  172,  173,  174,  175,  176,  177,
      178,  179,  180,  181,  182,  183,  184,  185,  186,  187,
      188,  189,  190,  191,  192,  193,  194,  195,  196,  197,
      198,  199,  200,  201,  202,  203,  204,  205,  206,  207,
      208,  209,  210,  211,  212,  213,  214,  215,  216,  217,
      218,  219,  220,  221,  222,  223,  224,  225,  226,  227,

      229,  230,  231,  232,  233,  234,  235,  236,  237,  239
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "grammar\\lexer.l"
#line 2 "grammar\\lexer.l"

#include <QString>
#include "lexer.hpp"
	//eGlobal = 0;
	//eLocal =1;
extern int lineNumber;

typedef Language::Parser::token token;
QString buf;
#define yyterminate() return( token::END )
#define YY_NO_UNISTD_H // For msvc

#line 846 "D:\\FreeCAD-0.19.1-build\\src\\Mod\\kawasaki\\kawasaki\\\\kawasaki\\grammar\\lexer.cpp"

#line 848 "D:\\FreeCAD-0.19.1-build\\src\\Mod\\kawasaki\\kawasaki\\\\kawasaki\\grammar\\lexer.cpp"

#define INITIAL 0
#define SINGLE_LINE_COMMENT_STATE 1
#define TRANS_LINES_STATE 2

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin.rdbuf(std::cin.rdbuf());
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout.rdbuf(std::cout.rdbuf());
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 100 "grammar\\lexer.l"


#line 1041 "D:\\FreeCAD-0.19.1-build\\src\\Mod\\kawasaki\\kawasaki\\\\kawasaki\\grammar\\lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 441 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 814 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 111 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 111 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 112 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 102 "grammar\\lexer.l"
yy_push_state(SINGLE_LINE_COMMENT_STATE);
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 104 "grammar\\lexer.l"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 105 "grammar\\lexer.l"
{
		yy_pop_state(); 
	}
	YY_BREAK

case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 115 "grammar\\lexer.l"
{ lineNumber++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 117 "grammar\\lexer.l"
;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 118 "grammar\\lexer.l"
{
                                        yylval->sval = new QString( yytext );
                                        return token::String;
                                }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "grammar\\lexer.l"
{
                                                        yylval->dval = atof(yytext);
                                                        return token::Number;
                                                }
	YY_BREAK
case 8:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 130 "grammar\\lexer.l"
{
                                      yylval->ival = atoi(yytext);
                                       return token::LNumber;
                     }                                     
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 136 "grammar\\lexer.l"
{ return token::NumberType; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 137 "grammar\\lexer.l"
{ return token::TextType; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 138 "grammar\\lexer.l"
{ return token::VoidType; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 139 "grammar\\lexer.l"
{ return token::MOD;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 140 "grammar\\lexer.l"
{ return token::DECODE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 141 "grammar\\lexer.l"
{ return token::BY;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 142 "grammar\\lexer.l"
{ return token::SHIFT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 143 "grammar\\lexer.l"
{ return token::IF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 144 "grammar\\lexer.l"
{ return token::ELSE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 145 "grammar\\lexer.l"
{ return token::THEN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 146 "grammar\\lexer.l"
{ return token::While; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 147 "grammar\\lexer.l"
{ return token::PRINT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 148 "grammar\\lexer.l"
{ return token::RETURN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 149 "grammar\\lexer.l"
{return token::DISTANCE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 150 "grammar\\lexer.l"
{return token::TRANS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 151 "grammar\\lexer.l"
{ return token::STOP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 152 "grammar\\lexer.l"
{return token::BITS;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 153 "grammar\\lexer.l"
{return token::HOME;}      	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 154 "grammar\\lexer.l"
{return token::BASE;}    	
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 155 "grammar\\lexer.l"
{return token::TOOL;}    	
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 156 "grammar\\lexer.l"
{return token::TYPE;} 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 157 "grammar\\lexer.l"
{return token::VAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 158 "grammar\\lexer.l"
{return token::PULSE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 159 "grammar\\lexer.l"
{return token::TWAIT;}   	
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 160 "grammar\\lexer.l"
{return token::SIGNAL;}   
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 161 "grammar\\lexer.l"
{return token::GOTO;}  
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 162 "grammar\\lexer.l"
{return token::FUNC;}  
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 163 "grammar\\lexer.l"
{return token::SIG;} 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 164 "grammar\\lexer.l"
{return token::JMOVE;}   
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 165 "grammar\\lexer.l"
{return token::SWAIT;} 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 166 "grammar\\lexer.l"
{return token::END_ST;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 167 "grammar\\lexer.l"
{return token::END_DOT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 168 "grammar\\lexer.l"
{return token::AND;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 169 "grammar\\lexer.l"
{return token::OR;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 170 "grammar\\lexer.l"
{return token::SWITCH;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 171 "grammar\\lexer.l"
{return token::CALL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 172 "grammar\\lexer.l"
{return token::CASE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 173 "grammar\\lexer.l"
{return token::DEFAULT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 174 "grammar\\lexer.l"
{return token::FNULL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 175 "grammar\\lexer.l"
{return token::OF;}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 176 "grammar\\lexer.l"
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 177 "grammar\\lexer.l"
{return token::DEFINES;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 178 "grammar\\lexer.l"
{return token::DEFINES;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 179 "grammar\\lexer.l"
{return token::JOINTS;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 180 "grammar\\lexer.l"
{return token::TRANS_DOT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 181 "grammar\\lexer.l"
{return token::FTRUE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 182 "grammar\\lexer.l"
{return token::FFALSE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 183 "grammar\\lexer.l"
{return token::LMOVE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 184 "grammar\\lexer.l"
{return token::DO;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 185 "grammar\\lexer.l"
{return token::UNTIL;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 186 "grammar\\lexer.l"
{return token::ALIGN;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 187 "grammar\\lexer.l"
{return token::BREAK;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 188 "grammar\\lexer.l"
{return token::HERE;}    
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 189 "grammar\\lexer.l"
{return token::DECOMPOSE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 190 "grammar\\lexer.l"
{return token::SPEED;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 191 "grammar\\lexer.l"
{return token::JAPPRO;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 192 "grammar\\lexer.l"
{return token::C1MOVE;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 193 "grammar\\lexer.l"
{return token::LAPPRO;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 194 "grammar\\lexer.l"
{return token::ACCURACY;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 195 "grammar\\lexer.l"
{return token::DRIVE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 196 "grammar\\lexer.l"
{return token::DRAW;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 197 "grammar\\lexer.l"
{return token::POINT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 198 "grammar\\lexer.l"
{return token::WEIGHT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 199 "grammar\\lexer.l"
{return token::LDEPART;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 200 "grammar\\lexer.l"
{return token::POINT_X;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 201 "grammar\\lexer.l"
{return token::POINT_Z;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 202 "grammar\\lexer.l"
{return token::POINT_OAT;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 203 "grammar\\lexer.l"
{return token::TDRAW;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 204 "grammar\\lexer.l"
{return token::TCP_SEND;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 205 "grammar\\lexer.l"
{return token::TCP_CLOSE;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 206 "grammar\\lexer.l"
{return token::TCP_RECV;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 207 "grammar\\lexer.l"
{return token::TCP_STATUS;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 208 "grammar\\lexer.l"
{return token::TCP_CONNECT;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 209 "grammar\\lexer.l"
{return token::MM_S;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 210 "grammar\\lexer.l"
{return token::MM_MIN;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 211 "grammar\\lexer.l"
{return token::ALWAYS;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 212 "grammar\\lexer.l"
{return token::FOR;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 213 "grammar\\lexer.l"
{return token::PAUSE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 214 "grammar\\lexer.l"
{return token::TO;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 215 "grammar\\lexer.l"
{return token::FINE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 216 "grammar\\lexer.l"
{return token::UNTIL;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 217 "grammar\\lexer.l"
{return token::STEP;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 218 "grammar\\lexer.l"
{return token::ASS;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 219 "grammar\\lexer.l"
{ return token::EQ; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 220 "grammar\\lexer.l"
{ return token::GE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 221 "grammar\\lexer.l"
{ return token::NE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 222 "grammar\\lexer.l"
{ return token::LE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 223 "grammar\\lexer.l"
{ return token::LR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 224 "grammar\\lexer.l"
{ return token::RR; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 225 "grammar\\lexer.l"
{ return token::COMMA; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 226 "grammar\\lexer.l"
{ return token::LC; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 227 "grammar\\lexer.l"
{ return token::RC; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 229 "grammar\\lexer.l"
{return token::JIN;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 230 "grammar\\lexer.l"
{ return token::ADD; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 231 "grammar\\lexer.l"
{ return token::SUB; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 232 "grammar\\lexer.l"
{ return token::MUL; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 233 "grammar\\lexer.l"
{ return token::COLON; }  
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 234 "grammar\\lexer.l"
{return token::LT;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 235 "grammar\\lexer.l"
{return token::GT;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 236 "grammar\\lexer.l"
{return token::DOLAR;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 237 "grammar\\lexer.l"
{return token::JOINTS_VAR;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 239 "grammar\\lexer.l"
{
                                                        yylval->sval = new QString( yytext );
                                                        return( token::Identifier );
                                             }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 246 "grammar\\lexer.l"
ECHO;
	YY_BREAK
#line 1699 "D:\\FreeCAD-0.19.1-build\\src\\Mod\\kawasaki\\kawasaki\\\\kawasaki\\grammar\\lexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLE_LINE_COMMENT_STATE):
case YY_STATE_EOF(TRANS_LINES_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 441 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 441 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 440);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, char* yy_bp)
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream& input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	yyrestart( *input_file );
}
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_input_file = (&file == 0) ? NULL : file.rdbuf();
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int _new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 246 "grammar\\lexer.l"


